
-- GET ALL LATEST PACKAGES FOR ALL DISTRIBUTIONS
SELECT D.NAME, P.NAME, V.VAL, CREATED FROM DISTRIBUTION_PACKAGE_VERSION
    JOIN DISTRIBUTION AS D
        ON DISTRIBUTION_PACKAGE_VERSION.DISTRIBUTION_ID = D.ID
    JOIN PACKAGE AS P
        ON DISTRIBUTION_PACKAGE_VERSION.PACKAGE_ID = P.ID
    JOIN VERSION AS V
        ON DISTRIBUTION_PACKAGE_VERSION.VERSION_ID = V.ID
    WHERE TYPE = 1